Feat/add user friends
isaacmsl/bora-pagar pull request #120
Opened 2024-01-10 04:06 UTC by Kywal

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Mesmo padrão de código do projeto
- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [x] A PR está relacionada a uma ou mais issue
- [x] Relacionei todas as issues na seção de "Development" da PR
- [x] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

Necessidade de conexão entre usuários, veja #13. 

**O que foi feito**

- Implementação do atributo friends e suas respectivas rotas/métodos de adição e remoção
- Implementação de testes para esses métdos
- Atualização do Insomnia.json com as novas rotas e uma variável de ambiente  `_.friendId`

2024-01-10 04:09 UTC, isaacmsl commented
O _lazy_ foi suficiente para que ele não entrasse num loop infinito quando buscasse um usuário A que possui um usuário B como amigo e esse usuário B tem o usuário A como amigo também?

2024-01-10 04:12 UTC, Kywal commented
Bom ponto, ainda não foi testado. 

On it. 🏃‍♂️

2024-01-10 04:57 UTC, Kywal commented
Bug também encontrado: #124

Att: Já foi corrigido ✅

2024-01-10 19:29 UTC, RamonJales approved these changes

2024-01-10 20:29 UTC, isaacmsl requested changes

2024-01-10 20:29 UTC, isaacmsl commented on backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
> +    public ResponseEntity<List<UserModel>> findFriends(@RequestParam String googleId) {
Isso é pros administradores.
A rota pública só vai carregar os amigos do usuário logado (pega credential apenas).
É bom ter os dois eu acho.

2024-01-15 04:41 UTC, isaacmsl commented
> Isso é pros administradores.
A rota pública só vai carregar os amigos do usuário logado (pega credential apenas).
É bom ter os dois eu acho.

Adicionei o `/forceFriends` e mantive o `/friends` para o usuário autenticado público (esse "force" vem do padrão que estamos seguindo para "forçar alguma coisa" e isso dá a entender que só quem tem força na API é o ADMIN).

2024-01-16 22:57 UTC, isaacmsl approved these changes
LGTM

2024-01-18 19:25 UTC, merged