Fix/interested user error
isaacmsl/bora-pagar pull request #137
Opened 2024-01-10 17:24 UTC by IanGabriel12

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Mesmo padrão de código do projeto
- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [ ] A PR está relacionada a uma ou mais issue
- [ ] Relacionei todas as issues na seção de "Development" da PR
- [x] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

Há um erro onde o front espera uma resposta do backend que é nula. Isto gera o seguinte erro:
 
![image](https://github.com/isaacmsl/bora-pagar/assets/50637958/1f8c688e-c630-476d-9628-e16e1aa7ac26)

**O que foi feito**

Correção do erro seguindo o padrão da resposta do backend

2024-01-10 17:41 UTC, isaacmsl approved these changes
LGTM

2024-01-11 21:09 UTC, isaacmsl reviewed
Não entendi como isso resolve o "erro" (preciso de mais detalhes aqui pois não foi dito como reproduzir o erro, o que é esperado etc.). Com certeza é uma refatoração.

2024-01-11 21:12 UTC, isaacmsl requested changes
Não entendi como isso resolve o "erro" (preciso de mais detalhes aqui pois ão foi dito como reproduzir o erro, o que é esperado etc.)

2024-01-12 18:36 UTC, isaacmsl commented
Testei em produção e não ocorre erro algum.

2024-01-12 18:47 UTC, closed without merging

2024-01-12 18:48 UTC, IanGabriel12 commented
O problema aconteceu apenas localmente pois eu não tinha as credenciais corretas no backend. A solução não se faz necessária