Feat/front project using docker
isaacmsl/bora-pagar pull request #14
Opened 2023-12-26 21:16 UTC by IanGabriel12

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Mesmo padrão de código do projeto
- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [x] A PR está relacionada a uma ou mais issue
- [x] Relacionei todas as issues na seção de "Issues" da PR 
- [x] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

Precisamos iniciar a configuração do projeto do frontend, incluindo a criação de um container docker para que nenhum dos desenvolvedores precise instalar outras ferramentas.

**O que foi feito**

Inicialização do projeto front e configuração do docker. Além de uma documentação de como rodar o projeto

**O que faltou desenvolver**

Falta os outros devs rodarem o projeto em suas máquinas para checar se tudo está nos conformes

2023-12-26 23:06 UTC, isaacmsl commented
Como foi iniciado o projeto?
Digo, tu escolheu yarn e tinha outras opções também (No/Yes).

2023-12-26 23:13 UTC, isaacmsl commented
OBS: O campo "Relacionei todas as issues na seção de "Issues" da PR" não foi executado de verdade.
É verdade que o nome da seção não é mais "Issues" e sim "Development".

2023-12-26 23:19 UTC, IanGabriel12 commented
> Como foi iniciado o projeto? [...]

Foi criado com o comando:
```bash
yarn create vite frontend --template vue-ts
```
Não houve nenhum prompt de perguntas de Yes/No

2023-12-26 23:40 UTC, isaacmsl commented
Entendi. Não sei se seria o mais adequado. Ele só coloca Typescript no projeto?

2023-12-27 01:09 UTC, isaacmsl requested changes
Precisa de mais coisas... Prettier, Typescripte, ESLint etc.

2023-12-27 15:15 UTC, isaacmsl approved these changes
LGTM :heavy_check_mark:

2023-12-27 15:27 UTC, merged