feat: github icon
isaacmsl/bora-pagar pull request #149
Opened 2024-01-12 01:01 UTC by DanilloFonseca

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [ ] Mesmo padrão de código do projeto
- [ ] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [ ] A PR está relacionada a uma ou mais issue
- [ ] Relacionei todas as issues na seção de "Development" da PR
- [ ] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

**O que foi feito**

**Screenshots**

**O que faltou desenvolver**

2024-01-12 03:59 UTC, Kywal requested changes
Não gostei do posicionamento, ficou meio estranho. Mas a ideia é ótima!

2024-01-12 17:34 UTC, isaacmsl requested changes
> Não gostei do posicionamento, ficou meio estranho. Mas a ideia é ótima!

Peraí, @Kywal ... Dá Request Changes mas fala algo objetivo. Você tem alguma sugestão de posicionamento?
Acho que se tirasse os paddings laterais ficaria melhor. Ainda dá garante uma certa margem de acessibilidade com os paddings verticais.

2024-01-12 23:52 UTC, isaacmsl approved these changes
Entendi tua ideia. Quando se trata de uma propriedade que possui valor zero a unidade não importa: `0px, 0%, 0rem` etc. Tudo pode ser resumido para `0` (`padding-left: 0;`). Acho que é pagável esse preço de perder o padding lateral esquerdo. Mantivemos uma certa acessibilidade para os mobiles com os paddings restantes.

2024-01-13 01:41 UTC, IanGabriel12 approved these changes

2024-01-13 02:54 UTC, Kywal commented
> Peraí, @Kywal ... Dá Request Changes mas fala algo objetivo. Você tem alguma sugestão de posicionamento? 

Desculpa, tava sem ideia na hora. @DanilloFonseca você pode testar colocar ele entre o *bora Pagar* e os botões? Outra alternativa, que eu gosto mais, é de ficar no footer.

2024-01-15 04:20 UTC, isaacmsl commented
PR ficou encalhada. Não faz sentido ficar tentando outras opções nessa altura.
Essas alternativas devem ser testadas em outras PRs futuras.
@Kywal revise novamente a PR, por favor.

2024-01-15 13:27 UTC, merged