Update README.md
isaacmsl/bora-pagar pull request #156
Opened 2024-01-12 02:48 UTC by isaacmsl

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Mesmo padrão de código do projeto
- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [ ] A PR está relacionada a uma ou mais issue
- [ ] Relacionei todas as issues na seção de "Development" da PR
- [ ] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

O nosso projeto precisa ser mais apresentável.

**O que foi feito**

Um README no capricho.

2024-01-12 04:13 UTC, DanilloFonseca commented
O vídeo não carrega. Como outras pessoas já reclamaram disso, creio que não seja algo exclusivo do meu pc. Minha sugestão é uppar o vídeo no youtube (na parte privada) e adicionar outro hiperlink no readme: "Clique aqui para acessar o vídeo apresentando o projeto". Outra questão é o idioma do readme, fizemos commits e branchs em inglês, o readme não deveria ser um inglês também? ( Até pq eu adoraria uma vaguinha de dev na europa ou no canadá xD ).

2024-01-12 04:19 UTC, Kywal commented
O vídeo de apresentação da plataforma no youtube é uma boa, mas para o readme acredito que a melhor opção é um gif só mostrando a cara da aplicação.

2024-01-12 04:21 UTC, Kywal requested changes
Falta uns emojis, umas fotinhas dos símbolos das stacks, uma corzinha a mais!

2024-01-12 14:09 UTC, isaacmsl commented
> Outra questão é o idioma do readme, fizemos commits e branchs em inglês, o readme não deveria ser um inglês também?

Acho que é melhor em português para ser mais acessível para contribuidores aqui da UFRN.

2024-01-12 14:31 UTC, DanilloFonseca commented
> > O vídeo de apresentação da plataforma no youtube é uma boa, mas para o readme acredito que a melhor opção é um gif só mostrando a cara da aplicação.
> 
> Posso estar enganado mas não existe GIF em Markdown. Ou é imagem ou é vídeo.

https://stackoverflow.com/questions/34341808/is-there-a-way-to-add-an-animated-gif-to-a-markdown-file

2024-01-12 17:31 UTC, isaacmsl commented
> Falta uns emojis, umas fotinhas dos símbolos das stacks, uma corzinha a mais!

Pode me ajudar, @Kywal ?

2024-01-12 17:32 UTC, Kywal commented
ajudo sim, meu bom. Daqui a pouco vejo isso.

2024-01-12 21:59 UTC, RamonJales approved these changes
Noussa, muito lindo!

2024-01-12 22:31 UTC, DanilloFonseca requested changes
No celular, as fotos dos contribuidores ficam completamente irregulares. Kywal meio que sumiu

2024-01-13 00:33 UTC, isaacmsl commented
> No celular, as fotos dos contribuidores ficam completamente irregulares. Kywal meio que sumiu

Eu notei que é por causa do @ dele, então precisei colocar Kyyyyywal para ele ficar mais ou menos como os outros nicknames. Outra coisa foi que eu "quebrei" a linha em duas de três colunas. O problema é que é uma tabela então ficou um espaço vazio (isso quer dizer, "pode ser você o próximo" , kkkkkkkkk)

![Screenshot from 2024-01-12 21-30-34](https://github.com/isaacmsl/bora-pagar/assets/31693006/d474b45d-553e-4c75-a081-2da4cea1a071)

2024-01-13 01:22 UTC, isaacmsl commented
Faz sentido adicionar vídeos tutoriais para quem quiser rodar o nosso sistema. Um primeiro por exemplo é como criar um banco no Mongo Cloud para poder rodar o backend com um banco personalizado. Eis o link:

https://youtu.be/LvEB7efljfQ

Vou adicionar no README.md também.

2024-01-13 02:19 UTC, isaacmsl commented
Julgo não essencial o RC de @Kywal . Essa estilização pode ser feita após essa PR ser mergeado pois algumas pessoas podem estar perdendo o interesse por não saber como rodar o sistema. É urgente essa PR!

2024-01-13 02:21 UTC, Kywal commented
ta bommmm, vou liberar. tava de férias aqui calmô

2024-01-13 02:21 UTC, Kywal approved these changes
ficou bom, vou tentar aprimorar depois

2024-01-13 02:48 UTC, DanilloFonseca approved these changes
LGTM

2024-01-13 02:49 UTC, merged

2024-01-13 02:52 UTC, RamonJales reviewed
ok