fix: `pagarei` button gets unaligned
isaacmsl/bora-pagar pull request #168
Opened 2024-01-13 03:27 UTC by Kywal

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Mesmo padrão de código do projeto
- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [x] A PR está relacionada a uma ou mais issue
- [x] Relacionei todas as issues na seção de "Development" da PR
- [ ] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

Veja #145 

**O que foi feito**

O componente button foi realinhado a partir de uma nova div.

**Screenshots**

***Resultado atual***
![image](https://github.com/isaacmsl/bora-pagar/assets/69535401/b1473a31-189b-4663-ae65-c069aa4fbf5c)

2024-01-13 10:58 UTC, IanGabriel12 requested changes
Já existe uma div `.subject-actions` que envolve tanto o botão quanto as informações de quem está pagando. Bastaria um `text-align: right` nela.

Acho que seria melhor pois o componente de botão é bem genérico e você está aplicando estilização para ele ser usado em um lugar específico. Quando formos usar ele em outros lugares, isso pode quebrar.

2024-01-13 13:15 UTC, isaacmsl requested changes
Concordo com o problema em generalizar isso no `Button`. Sobre o que @IanGabriel12  falou, sou muito crítico em utilizar alinhamento de texto para alinhar componentes: é uma total gambiarra! O `justify-content` e `align-items` estão no CSS para isso. Fez muito bem em utilizar o `justify-content` @Kywal , só que está no lugar errado. Um erro comum de CSS é não perceber quem precisar ser estilizado para alinhar um componente A. Ponho margin em A? Nãaaaaaaaaao, por favooor. Na grande maioria das vezes você olha pro pai de A e estiliza de lá.

2024-01-18 18:37 UTC, IanGabriel12 approved these changes
LGTM

2024-01-18 19:23 UTC, isaacmsl approved these changes
LGTM

2024-01-18 19:23 UTC, merged